### ISSUE TITLE
Self-Hosted - Docker image build results in crash using k8s

### ISSUE THREAD

**Issue by mavrick** [papercups-io/papercups#339]
**Describe the bug**
Docker launch in k8s environment results in `Could not find Hex, which is needed to build dependency :credo`

**To Reproduce**
1. Deploy papercups/papercups:latest https://hub.docker.com/r/papercups/papercups 
2. Check logs

**Expected behavior**
hex to be installed during docker build on hub

**Additional context**

Logs from k8s:

```text
Could not find Hex, which is needed to build dependency :credo
** (Mix) Could not find an SCM for dependency :credo from ChatApi.MixProject
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
```

deployment.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: papercups
  labels:
    app: papercups
spec:
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: papercups
  template:
    metadata:
      labels:
        app: papercups
    spec:
      containers:
      - name: papercups
        image: papercups/papercups:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/src/app/docker-entrypoint.sh"]
        env:
        - name: DOMAIN
          value: "domain.com"
        - name: DATABASE_URL
          value: "ecto://papercups:xxxxxxxx@postgres-ingress.db/papercups"
        - name: BACKEND_URL
          value: "https://chat.domain.com"
        - name: PAPERCUPS_SLACK_CLIENT_ID
          value: "xxxxxxxx"
        - name: PAPERCUPS_SLACK_CLIENT_SECRET
          value: "xxxxxxxx"
        ports:
        - containerPort: 3000
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 120
```

I'm not familiar with Elixer, the apt-get command inside Dockerfile appears solid from first glance.
