### ISSUE TITLE
Markdown rendering in chat messages don't properly render h1 tags

### ISSUE THREAD

**Issue by rhonsby** [papercups-io/papercups#758]
**Describe the bug**
Conversations on the conversation page render messages with markdown, but it doesn't seem to be rendering h1 tags properly. h1 tags are smaller than h2 and h3s. I didn't look too deeply into it, but there seems to be some complex css rules that might be causing this.

**To Reproduce**
1. Go to `/conversations/all` and click on a conversation.
2. Send a message with three different headers:
```
# h1 tag
## h2 tag
### h3 tag
```
3. Observe how the h1 tag is smaller than the other tags when it should be the biggest one.

**Expected behavior**
The h1 tag should be bigger than the h2 and h3 tags.

**Screenshots**
![image](https://user-images.githubusercontent.com/1361509/115439664-d4343380-a1dc-11eb-9f72-aa3e045d24f5.png)

**Comment by fmterrorf** [comment]
I noticed the default Firefox stylesheet have this code `resource://gre-resources/html.css`
```css
h5,
:is(article, aside, nav, section)
:is(article, aside, nav, section)
:is(article, aside, nav, section)
:is(article, aside, nav, section)
h1 {
  display: block;
  font-size: 0.83em;
  font-weight: bold;
  margin-block-start: 1.67em;
  margin-block-end: 1.67em;
}
```
Which shrinks the `h1` element to 0.83em 
![h1](https://user-images.githubusercontent.com/77761194/116756033-a6af6d00-a9c8-11eb-9d2d-1534d8e85fb0.png)

I guess we can force it to use `2em`
